#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovDepAdjustCheck.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JmgjjPreliminary")]
	public partial class LinqToPreJctzDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertA037preJctz(A037preJctz instance);
    partial void UpdateA037preJctz(A037preJctz instance);
    partial void DeleteA037preJctz(A037preJctz instance);
    partial void Insertt_account(t_account instance);
    partial void Updatet_account(t_account instance);
    partial void Deletet_account(t_account instance);
    #endregion
		
		public LinqToPreJctzDataContext() : 
				base(global::GovDepAdjustCheck.Properties.Settings.Default.JmgjjPreliminaryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToPreJctzDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToPreJctzDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToPreJctzDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToPreJctzDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<A037preJctz> A037preJctzs
		{
			get
			{
				return this.GetTable<A037preJctz>();
			}
		}
		
		public System.Data.Linq.Table<t_account> t_accounts
		{
			get
			{
				return this.GetTable<t_account>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A037preJctz")]
	public partial class A037preJctz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _responsNum;
		
		private System.Nullable<int> _areaCode;
		
		private string _uAccount;
		
		private string _uName;
		
		private System.Nullable<int> _aCount;
		
		private string _status;
		
		private string _agentName;
		
		private string _agentTel;
		
		private System.Nullable<System.DateTime> _ondate;
		
		private string _editor;
		
		private string _des;
		
		private System.Nullable<System.DateTime> _edittime;
		
		private string _auditor;
		
		private System.Nullable<System.DateTime> _audittime;
		
		private System.Nullable<bool> _isdel;
		
		private System.Data.Linq.Binary _tsp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnresponsNumChanging(string value);
    partial void OnresponsNumChanged();
    partial void OnareaCodeChanging(System.Nullable<int> value);
    partial void OnareaCodeChanged();
    partial void OnuAccountChanging(string value);
    partial void OnuAccountChanged();
    partial void OnuNameChanging(string value);
    partial void OnuNameChanged();
    partial void OnaCountChanging(System.Nullable<int> value);
    partial void OnaCountChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnagentNameChanging(string value);
    partial void OnagentNameChanged();
    partial void OnagentTelChanging(string value);
    partial void OnagentTelChanged();
    partial void OnondateChanging(System.Nullable<System.DateTime> value);
    partial void OnondateChanged();
    partial void OneditorChanging(string value);
    partial void OneditorChanged();
    partial void OndesChanging(string value);
    partial void OndesChanged();
    partial void OnedittimeChanging(System.Nullable<System.DateTime> value);
    partial void OnedittimeChanged();
    partial void OnauditorChanging(string value);
    partial void OnauditorChanged();
    partial void OnaudittimeChanging(System.Nullable<System.DateTime> value);
    partial void OnaudittimeChanged();
    partial void OnisdelChanging(System.Nullable<bool> value);
    partial void OnisdelChanged();
    partial void OntspChanging(System.Data.Linq.Binary value);
    partial void OntspChanged();
    #endregion
		
		public A037preJctz()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsNum", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string responsNum
		{
			get
			{
				return this._responsNum;
			}
			set
			{
				if ((this._responsNum != value))
				{
					this.OnresponsNumChanging(value);
					this.SendPropertyChanging();
					this._responsNum = value;
					this.SendPropertyChanged("responsNum");
					this.OnresponsNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> areaCode
		{
			get
			{
				return this._areaCode;
			}
			set
			{
				if ((this._areaCode != value))
				{
					this.OnareaCodeChanging(value);
					this.SendPropertyChanging();
					this._areaCode = value;
					this.SendPropertyChanged("areaCode");
					this.OnareaCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uAccount", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string uAccount
		{
			get
			{
				return this._uAccount;
			}
			set
			{
				if ((this._uAccount != value))
				{
					this.OnuAccountChanging(value);
					this.SendPropertyChanging();
					this._uAccount = value;
					this.SendPropertyChanged("uAccount");
					this.OnuAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uName", DbType="NVarChar(500)", UpdateCheck=UpdateCheck.Never)]
		public string uName
		{
			get
			{
				return this._uName;
			}
			set
			{
				if ((this._uName != value))
				{
					this.OnuNameChanging(value);
					this.SendPropertyChanging();
					this._uName = value;
					this.SendPropertyChanged("uName");
					this.OnuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aCount", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> aCount
		{
			get
			{
				return this._aCount;
			}
			set
			{
				if ((this._aCount != value))
				{
					this.OnaCountChanging(value);
					this.SendPropertyChanging();
					this._aCount = value;
					this.SendPropertyChanged("aCount");
					this.OnaCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agentName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string agentName
		{
			get
			{
				return this._agentName;
			}
			set
			{
				if ((this._agentName != value))
				{
					this.OnagentNameChanging(value);
					this.SendPropertyChanging();
					this._agentName = value;
					this.SendPropertyChanged("agentName");
					this.OnagentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agentTel", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string agentTel
		{
			get
			{
				return this._agentTel;
			}
			set
			{
				if ((this._agentTel != value))
				{
					this.OnagentTelChanging(value);
					this.SendPropertyChanging();
					this._agentTel = value;
					this.SendPropertyChanged("agentTel");
					this.OnagentTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ondate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ondate
		{
			get
			{
				return this._ondate;
			}
			set
			{
				if ((this._ondate != value))
				{
					this.OnondateChanging(value);
					this.SendPropertyChanging();
					this._ondate = value;
					this.SendPropertyChanged("ondate");
					this.OnondateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editor", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string editor
		{
			get
			{
				return this._editor;
			}
			set
			{
				if ((this._editor != value))
				{
					this.OneditorChanging(value);
					this.SendPropertyChanging();
					this._editor = value;
					this.SendPropertyChanged("editor");
					this.OneditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_des", DbType="NVarChar(500)", UpdateCheck=UpdateCheck.Never)]
		public string des
		{
			get
			{
				return this._des;
			}
			set
			{
				if ((this._des != value))
				{
					this.OndesChanging(value);
					this.SendPropertyChanging();
					this._des = value;
					this.SendPropertyChanged("des");
					this.OndesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edittime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> edittime
		{
			get
			{
				return this._edittime;
			}
			set
			{
				if ((this._edittime != value))
				{
					this.OnedittimeChanging(value);
					this.SendPropertyChanging();
					this._edittime = value;
					this.SendPropertyChanged("edittime");
					this.OnedittimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditor", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string auditor
		{
			get
			{
				return this._auditor;
			}
			set
			{
				if ((this._auditor != value))
				{
					this.OnauditorChanging(value);
					this.SendPropertyChanging();
					this._auditor = value;
					this.SendPropertyChanged("auditor");
					this.OnauditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audittime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> audittime
		{
			get
			{
				return this._audittime;
			}
			set
			{
				if ((this._audittime != value))
				{
					this.OnaudittimeChanging(value);
					this.SendPropertyChanging();
					this._audittime = value;
					this.SendPropertyChanged("audittime");
					this.OnaudittimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdel", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> isdel
		{
			get
			{
				return this._isdel;
			}
			set
			{
				if ((this._isdel != value))
				{
					this.OnisdelChanging(value);
					this.SendPropertyChanging();
					this._isdel = value;
					this.SendPropertyChanged("isdel");
					this.OnisdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsp", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary tsp
		{
			get
			{
				return this._tsp;
			}
			set
			{
				if ((this._tsp != value))
				{
					this.OntspChanging(value);
					this.SendPropertyChanging();
					this._tsp = value;
					this.SendPropertyChanged("tsp");
					this.OntspChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_account")]
	public partial class t_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _u_id;
		
		private string _Id_Card;
		
		private string _Name;
		
		private string _Account;
		
		private System.Nullable<System.DateTime> _workdate;
		
		private System.Nullable<System.DateTime> _c_date;
		
		private System.Nullable<int> _Bank;
		
		private System.Nullable<decimal> _Salary;
		
		private System.Nullable<decimal> _u_money;
		
		private System.Nullable<decimal> _i_money;
		
		private System.Nullable<decimal> _Money;
		
		private System.Nullable<decimal> _accrual;
		
		private System.Nullable<int> _Status;
		
		private string _remark;
		
		private int _sign_tag;
		
		private string _input_user;
		
		private System.DateTime _input_time;
		
		private string _sign_user;
		
		private System.Nullable<System.DateTime> _sign_time;
		
		private string _number_id;
		
		private string _u_name;
		
		private System.Nullable<decimal> _money_backup;
		
		private string _fgb_account;
		
		private string _u_account;
		
		private string _tel;
		
		private string _mobile;
		
		private string _bank_card;
		
		private System.Nullable<decimal> _Render_Money;
		
		private string _bank_u_name;
		
		private System.Nullable<System.DateTime> _end_date;
		
		private System.Nullable<int> _xml_id;
		
		private System.Nullable<System.DateTime> _fact_date;
		
		private System.Nullable<double> _bili;
		
		private System.Nullable<bool> _over_area_tag;
		
		private System.Nullable<int> _area_code;
		
		private string _corp_type;
		
		private string _corp_code;
		
		private System.Nullable<decimal> _u_bili;
		
		private string _ZhiFuMiMa;
		
		private System.Nullable<decimal> _i_bili;
		
		private string _account_backup;
		
		private System.Nullable<int> _noNumberId;
		
		private System.Nullable<bool> _is_loan_otherarea_tag;
		
		private string _render_city;
		
		private System.Nullable<decimal> _openMoney;
		
		private System.Nullable<bool> _is_id_card;
		
		private System.Nullable<System.DateTime> _modify_time;
		
		private string _modify_user;
		
		private System.Nullable<System.DateTime> _sign_modify_time;
		
		private string _sign_modify_user;
		
		private string _pwd;
		
		private string _EmpCode;
		
		private System.Nullable<int> _EmpID;
		
		private System.Nullable<decimal> _NewBalance;
		
		private string _GLMen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onu_idChanging(int value);
    partial void Onu_idChanged();
    partial void OnId_CardChanging(string value);
    partial void OnId_CardChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAccountChanging(string value);
    partial void OnAccountChanged();
    partial void OnworkdateChanging(System.Nullable<System.DateTime> value);
    partial void OnworkdateChanged();
    partial void Onc_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onc_dateChanged();
    partial void OnBankChanging(System.Nullable<int> value);
    partial void OnBankChanged();
    partial void OnSalaryChanging(System.Nullable<decimal> value);
    partial void OnSalaryChanged();
    partial void Onu_moneyChanging(System.Nullable<decimal> value);
    partial void Onu_moneyChanged();
    partial void Oni_moneyChanging(System.Nullable<decimal> value);
    partial void Oni_moneyChanged();
    partial void OnMoneyChanging(System.Nullable<decimal> value);
    partial void OnMoneyChanged();
    partial void OnaccrualChanging(System.Nullable<decimal> value);
    partial void OnaccrualChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Onsign_tagChanging(int value);
    partial void Onsign_tagChanged();
    partial void Oninput_userChanging(string value);
    partial void Oninput_userChanged();
    partial void Oninput_timeChanging(System.DateTime value);
    partial void Oninput_timeChanged();
    partial void Onsign_userChanging(string value);
    partial void Onsign_userChanged();
    partial void Onsign_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onsign_timeChanged();
    partial void Onnumber_idChanging(string value);
    partial void Onnumber_idChanged();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    partial void Onmoney_backupChanging(System.Nullable<decimal> value);
    partial void Onmoney_backupChanged();
    partial void Onfgb_accountChanging(string value);
    partial void Onfgb_accountChanged();
    partial void Onu_accountChanging(string value);
    partial void Onu_accountChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void Onbank_cardChanging(string value);
    partial void Onbank_cardChanged();
    partial void OnRender_MoneyChanging(System.Nullable<decimal> value);
    partial void OnRender_MoneyChanged();
    partial void Onbank_u_nameChanging(string value);
    partial void Onbank_u_nameChanged();
    partial void Onend_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onend_dateChanged();
    partial void Onxml_idChanging(System.Nullable<int> value);
    partial void Onxml_idChanged();
    partial void Onfact_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onfact_dateChanged();
    partial void OnbiliChanging(System.Nullable<double> value);
    partial void OnbiliChanged();
    partial void Onover_area_tagChanging(System.Nullable<bool> value);
    partial void Onover_area_tagChanged();
    partial void Onarea_codeChanging(System.Nullable<int> value);
    partial void Onarea_codeChanged();
    partial void Oncorp_typeChanging(string value);
    partial void Oncorp_typeChanged();
    partial void Oncorp_codeChanging(string value);
    partial void Oncorp_codeChanged();
    partial void Onu_biliChanging(System.Nullable<decimal> value);
    partial void Onu_biliChanged();
    partial void OnZhiFuMiMaChanging(string value);
    partial void OnZhiFuMiMaChanged();
    partial void Oni_biliChanging(System.Nullable<decimal> value);
    partial void Oni_biliChanged();
    partial void Onaccount_backupChanging(string value);
    partial void Onaccount_backupChanged();
    partial void OnnoNumberIdChanging(System.Nullable<int> value);
    partial void OnnoNumberIdChanged();
    partial void Onis_loan_otherarea_tagChanging(System.Nullable<bool> value);
    partial void Onis_loan_otherarea_tagChanged();
    partial void Onrender_cityChanging(string value);
    partial void Onrender_cityChanged();
    partial void OnopenMoneyChanging(System.Nullable<decimal> value);
    partial void OnopenMoneyChanged();
    partial void Onis_id_cardChanging(System.Nullable<bool> value);
    partial void Onis_id_cardChanged();
    partial void Onmodify_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodify_timeChanged();
    partial void Onmodify_userChanging(string value);
    partial void Onmodify_userChanged();
    partial void Onsign_modify_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onsign_modify_timeChanged();
    partial void Onsign_modify_userChanging(string value);
    partial void Onsign_modify_userChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnEmpCodeChanging(string value);
    partial void OnEmpCodeChanged();
    partial void OnEmpIDChanging(System.Nullable<int> value);
    partial void OnEmpIDChanged();
    partial void OnNewBalanceChanging(System.Nullable<decimal> value);
    partial void OnNewBalanceChanged();
    partial void OnGLMenChanging(string value);
    partial void OnGLMenChanged();
    #endregion
		
		public t_account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_id", DbType="Int NOT NULL")]
		public int u_id
		{
			get
			{
				return this._u_id;
			}
			set
			{
				if ((this._u_id != value))
				{
					this.Onu_idChanging(value);
					this.SendPropertyChanging();
					this._u_id = value;
					this.SendPropertyChanged("u_id");
					this.Onu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Card", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Id_Card
		{
			get
			{
				return this._Id_Card;
			}
			set
			{
				if ((this._Id_Card != value))
				{
					this.OnId_CardChanging(value);
					this.SendPropertyChanging();
					this._Id_Card = value;
					this.SendPropertyChanged("Id_Card");
					this.OnId_CardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="VarChar(255)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this.OnAccountChanging(value);
					this.SendPropertyChanging();
					this._Account = value;
					this.SendPropertyChanged("Account");
					this.OnAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> workdate
		{
			get
			{
				return this._workdate;
			}
			set
			{
				if ((this._workdate != value))
				{
					this.OnworkdateChanging(value);
					this.SendPropertyChanging();
					this._workdate = value;
					this.SendPropertyChanged("workdate");
					this.OnworkdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> c_date
		{
			get
			{
				return this._c_date;
			}
			set
			{
				if ((this._c_date != value))
				{
					this.Onc_dateChanging(value);
					this.SendPropertyChanging();
					this._c_date = value;
					this.SendPropertyChanged("c_date");
					this.Onc_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="Int")]
		public System.Nullable<int> Bank
		{
			get
			{
				return this._Bank;
			}
			set
			{
				if ((this._Bank != value))
				{
					this.OnBankChanging(value);
					this.SendPropertyChanging();
					this._Bank = value;
					this.SendPropertyChanged("Bank");
					this.OnBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salary", DbType="Money")]
		public System.Nullable<decimal> Salary
		{
			get
			{
				return this._Salary;
			}
			set
			{
				if ((this._Salary != value))
				{
					this.OnSalaryChanging(value);
					this.SendPropertyChanging();
					this._Salary = value;
					this.SendPropertyChanged("Salary");
					this.OnSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_money", DbType="Money")]
		public System.Nullable<decimal> u_money
		{
			get
			{
				return this._u_money;
			}
			set
			{
				if ((this._u_money != value))
				{
					this.Onu_moneyChanging(value);
					this.SendPropertyChanging();
					this._u_money = value;
					this.SendPropertyChanged("u_money");
					this.Onu_moneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_money", DbType="Money")]
		public System.Nullable<decimal> i_money
		{
			get
			{
				return this._i_money;
			}
			set
			{
				if ((this._i_money != value))
				{
					this.Oni_moneyChanging(value);
					this.SendPropertyChanging();
					this._i_money = value;
					this.SendPropertyChanged("i_money");
					this.Oni_moneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="Money")]
		public System.Nullable<decimal> Money
		{
			get
			{
				return this._Money;
			}
			set
			{
				if ((this._Money != value))
				{
					this.OnMoneyChanging(value);
					this.SendPropertyChanging();
					this._Money = value;
					this.SendPropertyChanged("Money");
					this.OnMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accrual", DbType="Money")]
		public System.Nullable<decimal> accrual
		{
			get
			{
				return this._accrual;
			}
			set
			{
				if ((this._accrual != value))
				{
					this.OnaccrualChanging(value);
					this.SendPropertyChanging();
					this._accrual = value;
					this.SendPropertyChanged("accrual");
					this.OnaccrualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(8000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sign_tag", DbType="Int NOT NULL")]
		public int sign_tag
		{
			get
			{
				return this._sign_tag;
			}
			set
			{
				if ((this._sign_tag != value))
				{
					this.Onsign_tagChanging(value);
					this.SendPropertyChanging();
					this._sign_tag = value;
					this.SendPropertyChanged("sign_tag");
					this.Onsign_tagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input_user", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string input_user
		{
			get
			{
				return this._input_user;
			}
			set
			{
				if ((this._input_user != value))
				{
					this.Oninput_userChanging(value);
					this.SendPropertyChanging();
					this._input_user = value;
					this.SendPropertyChanged("input_user");
					this.Oninput_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input_time", DbType="DateTime NOT NULL")]
		public System.DateTime input_time
		{
			get
			{
				return this._input_time;
			}
			set
			{
				if ((this._input_time != value))
				{
					this.Oninput_timeChanging(value);
					this.SendPropertyChanging();
					this._input_time = value;
					this.SendPropertyChanged("input_time");
					this.Oninput_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sign_user", DbType="VarChar(255)")]
		public string sign_user
		{
			get
			{
				return this._sign_user;
			}
			set
			{
				if ((this._sign_user != value))
				{
					this.Onsign_userChanging(value);
					this.SendPropertyChanging();
					this._sign_user = value;
					this.SendPropertyChanged("sign_user");
					this.Onsign_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sign_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> sign_time
		{
			get
			{
				return this._sign_time;
			}
			set
			{
				if ((this._sign_time != value))
				{
					this.Onsign_timeChanging(value);
					this.SendPropertyChanging();
					this._sign_time = value;
					this.SendPropertyChanged("sign_time");
					this.Onsign_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_id", DbType="VarChar(255)")]
		public string number_id
		{
			get
			{
				return this._number_id;
			}
			set
			{
				if ((this._number_id != value))
				{
					this.Onnumber_idChanging(value);
					this.SendPropertyChanging();
					this._number_id = value;
					this.SendPropertyChanged("number_id");
					this.Onnumber_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(255)")]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this.Onu_nameChanging(value);
					this.SendPropertyChanging();
					this._u_name = value;
					this.SendPropertyChanged("u_name");
					this.Onu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money_backup", DbType="Money")]
		public System.Nullable<decimal> money_backup
		{
			get
			{
				return this._money_backup;
			}
			set
			{
				if ((this._money_backup != value))
				{
					this.Onmoney_backupChanging(value);
					this.SendPropertyChanging();
					this._money_backup = value;
					this.SendPropertyChanged("money_backup");
					this.Onmoney_backupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fgb_account", DbType="VarChar(255)")]
		public string fgb_account
		{
			get
			{
				return this._fgb_account;
			}
			set
			{
				if ((this._fgb_account != value))
				{
					this.Onfgb_accountChanging(value);
					this.SendPropertyChanging();
					this._fgb_account = value;
					this.SendPropertyChanged("fgb_account");
					this.Onfgb_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_account", DbType="VarChar(255)")]
		public string u_account
		{
			get
			{
				return this._u_account;
			}
			set
			{
				if ((this._u_account != value))
				{
					this.Onu_accountChanging(value);
					this.SendPropertyChanging();
					this._u_account = value;
					this.SendPropertyChanged("u_account");
					this.Onu_accountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(255)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(255)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bank_card", DbType="VarChar(255)")]
		public string bank_card
		{
			get
			{
				return this._bank_card;
			}
			set
			{
				if ((this._bank_card != value))
				{
					this.Onbank_cardChanging(value);
					this.SendPropertyChanging();
					this._bank_card = value;
					this.SendPropertyChanged("bank_card");
					this.Onbank_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Render_Money", DbType="Money")]
		public System.Nullable<decimal> Render_Money
		{
			get
			{
				return this._Render_Money;
			}
			set
			{
				if ((this._Render_Money != value))
				{
					this.OnRender_MoneyChanging(value);
					this.SendPropertyChanging();
					this._Render_Money = value;
					this.SendPropertyChanged("Render_Money");
					this.OnRender_MoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bank_u_name", DbType="VarChar(255)")]
		public string bank_u_name
		{
			get
			{
				return this._bank_u_name;
			}
			set
			{
				if ((this._bank_u_name != value))
				{
					this.Onbank_u_nameChanging(value);
					this.SendPropertyChanging();
					this._bank_u_name = value;
					this.SendPropertyChanged("bank_u_name");
					this.Onbank_u_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml_id", DbType="Int")]
		public System.Nullable<int> xml_id
		{
			get
			{
				return this._xml_id;
			}
			set
			{
				if ((this._xml_id != value))
				{
					this.Onxml_idChanging(value);
					this.SendPropertyChanging();
					this._xml_id = value;
					this.SendPropertyChanged("xml_id");
					this.Onxml_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> fact_date
		{
			get
			{
				return this._fact_date;
			}
			set
			{
				if ((this._fact_date != value))
				{
					this.Onfact_dateChanging(value);
					this.SendPropertyChanging();
					this._fact_date = value;
					this.SendPropertyChanged("fact_date");
					this.Onfact_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bili", DbType="Float")]
		public System.Nullable<double> bili
		{
			get
			{
				return this._bili;
			}
			set
			{
				if ((this._bili != value))
				{
					this.OnbiliChanging(value);
					this.SendPropertyChanging();
					this._bili = value;
					this.SendPropertyChanged("bili");
					this.OnbiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_over_area_tag", DbType="Bit")]
		public System.Nullable<bool> over_area_tag
		{
			get
			{
				return this._over_area_tag;
			}
			set
			{
				if ((this._over_area_tag != value))
				{
					this.Onover_area_tagChanging(value);
					this.SendPropertyChanging();
					this._over_area_tag = value;
					this.SendPropertyChanged("over_area_tag");
					this.Onover_area_tagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_code", DbType="Int")]
		public System.Nullable<int> area_code
		{
			get
			{
				return this._area_code;
			}
			set
			{
				if ((this._area_code != value))
				{
					this.Onarea_codeChanging(value);
					this.SendPropertyChanging();
					this._area_code = value;
					this.SendPropertyChanged("area_code");
					this.Onarea_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_corp_type", DbType="VarChar(20)")]
		public string corp_type
		{
			get
			{
				return this._corp_type;
			}
			set
			{
				if ((this._corp_type != value))
				{
					this.Oncorp_typeChanging(value);
					this.SendPropertyChanging();
					this._corp_type = value;
					this.SendPropertyChanged("corp_type");
					this.Oncorp_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_corp_code", DbType="VarChar(255)")]
		public string corp_code
		{
			get
			{
				return this._corp_code;
			}
			set
			{
				if ((this._corp_code != value))
				{
					this.Oncorp_codeChanging(value);
					this.SendPropertyChanging();
					this._corp_code = value;
					this.SendPropertyChanged("corp_code");
					this.Oncorp_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_bili", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> u_bili
		{
			get
			{
				return this._u_bili;
			}
			set
			{
				if ((this._u_bili != value))
				{
					this.Onu_biliChanging(value);
					this.SendPropertyChanging();
					this._u_bili = value;
					this.SendPropertyChanged("u_bili");
					this.Onu_biliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZhiFuMiMa", DbType="VarChar(255)")]
		public string ZhiFuMiMa
		{
			get
			{
				return this._ZhiFuMiMa;
			}
			set
			{
				if ((this._ZhiFuMiMa != value))
				{
					this.OnZhiFuMiMaChanging(value);
					this.SendPropertyChanging();
					this._ZhiFuMiMa = value;
					this.SendPropertyChanged("ZhiFuMiMa");
					this.OnZhiFuMiMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_bili", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> i_bili
		{
			get
			{
				return this._i_bili;
			}
			set
			{
				if ((this._i_bili != value))
				{
					this.Oni_biliChanging(value);
					this.SendPropertyChanging();
					this._i_bili = value;
					this.SendPropertyChanged("i_bili");
					this.Oni_biliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_backup", DbType="VarChar(255)")]
		public string account_backup
		{
			get
			{
				return this._account_backup;
			}
			set
			{
				if ((this._account_backup != value))
				{
					this.Onaccount_backupChanging(value);
					this.SendPropertyChanging();
					this._account_backup = value;
					this.SendPropertyChanged("account_backup");
					this.Onaccount_backupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noNumberId", DbType="Int")]
		public System.Nullable<int> noNumberId
		{
			get
			{
				return this._noNumberId;
			}
			set
			{
				if ((this._noNumberId != value))
				{
					this.OnnoNumberIdChanging(value);
					this.SendPropertyChanging();
					this._noNumberId = value;
					this.SendPropertyChanged("noNumberId");
					this.OnnoNumberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_loan_otherarea_tag", DbType="Bit")]
		public System.Nullable<bool> is_loan_otherarea_tag
		{
			get
			{
				return this._is_loan_otherarea_tag;
			}
			set
			{
				if ((this._is_loan_otherarea_tag != value))
				{
					this.Onis_loan_otherarea_tagChanging(value);
					this.SendPropertyChanging();
					this._is_loan_otherarea_tag = value;
					this.SendPropertyChanged("is_loan_otherarea_tag");
					this.Onis_loan_otherarea_tagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_render_city", DbType="VarChar(255)")]
		public string render_city
		{
			get
			{
				return this._render_city;
			}
			set
			{
				if ((this._render_city != value))
				{
					this.Onrender_cityChanging(value);
					this.SendPropertyChanging();
					this._render_city = value;
					this.SendPropertyChanged("render_city");
					this.Onrender_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_openMoney", DbType="Money")]
		public System.Nullable<decimal> openMoney
		{
			get
			{
				return this._openMoney;
			}
			set
			{
				if ((this._openMoney != value))
				{
					this.OnopenMoneyChanging(value);
					this.SendPropertyChanging();
					this._openMoney = value;
					this.SendPropertyChanged("openMoney");
					this.OnopenMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_id_card", DbType="Bit")]
		public System.Nullable<bool> is_id_card
		{
			get
			{
				return this._is_id_card;
			}
			set
			{
				if ((this._is_id_card != value))
				{
					this.Onis_id_cardChanging(value);
					this.SendPropertyChanging();
					this._is_id_card = value;
					this.SendPropertyChanged("is_id_card");
					this.Onis_id_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modify_time
		{
			get
			{
				return this._modify_time;
			}
			set
			{
				if ((this._modify_time != value))
				{
					this.Onmodify_timeChanging(value);
					this.SendPropertyChanging();
					this._modify_time = value;
					this.SendPropertyChanged("modify_time");
					this.Onmodify_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_user", DbType="VarChar(255)")]
		public string modify_user
		{
			get
			{
				return this._modify_user;
			}
			set
			{
				if ((this._modify_user != value))
				{
					this.Onmodify_userChanging(value);
					this.SendPropertyChanging();
					this._modify_user = value;
					this.SendPropertyChanged("modify_user");
					this.Onmodify_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sign_modify_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> sign_modify_time
		{
			get
			{
				return this._sign_modify_time;
			}
			set
			{
				if ((this._sign_modify_time != value))
				{
					this.Onsign_modify_timeChanging(value);
					this.SendPropertyChanging();
					this._sign_modify_time = value;
					this.SendPropertyChanged("sign_modify_time");
					this.Onsign_modify_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sign_modify_user", DbType="VarChar(255)")]
		public string sign_modify_user
		{
			get
			{
				return this._sign_modify_user;
			}
			set
			{
				if ((this._sign_modify_user != value))
				{
					this.Onsign_modify_userChanging(value);
					this.SendPropertyChanging();
					this._sign_modify_user = value;
					this.SendPropertyChanged("sign_modify_user");
					this.Onsign_modify_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpCode", DbType="NVarChar(50)")]
		public string EmpCode
		{
			get
			{
				return this._EmpCode;
			}
			set
			{
				if ((this._EmpCode != value))
				{
					this.OnEmpCodeChanging(value);
					this.SendPropertyChanging();
					this._EmpCode = value;
					this.SendPropertyChanged("EmpCode");
					this.OnEmpCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Int")]
		public System.Nullable<int> EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewBalance", DbType="Money")]
		public System.Nullable<decimal> NewBalance
		{
			get
			{
				return this._NewBalance;
			}
			set
			{
				if ((this._NewBalance != value))
				{
					this.OnNewBalanceChanging(value);
					this.SendPropertyChanging();
					this._NewBalance = value;
					this.SendPropertyChanged("NewBalance");
					this.OnNewBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLMen", DbType="VarChar(100)")]
		public string GLMen
		{
			get
			{
				return this._GLMen;
			}
			set
			{
				if ((this._GLMen != value))
				{
					this.OnGLMenChanging(value);
					this.SendPropertyChanging();
					this._GLMen = value;
					this.SendPropertyChanged("GLMen");
					this.OnGLMenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
